apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "libero-reviewer.fullname" . }}-continuum-adaptor
  labels:
    app.kubernetes.io/name: {{ include "libero-reviewer.name" . }}--continuum-adaptor
    helm.sh/chart: {{ include "libero-reviewer.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: continuum-adaptor
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "libero-reviewer.name" . }}--continuum-adaptor
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: continuum-adaptor
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "libero-reviewer.name" . }}--continuum-adaptor
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: continuum-adaptor
    spec:
      containers:
        - name: {{ .Chart.Name }}-continuum-adaptor
          image: "{{ .Values.continuumAdaptor.image.repository }}:{{ .Values.continuumAdaptor.image.tag }}"
          imagePullPolicy: {{ .Values.continuumAdaptor.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.continuumAdaptor.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          env:
            - name: PORT
              value: {{ .Values.continuumAdaptor.port | quote }}
            - name: LOGIN_URL
              value: {{ .Values.continuumAdaptor.loginUrl | quote }}
            - name: LOGIN_RETURN_URL
              value: "https://{{ .Values.ingress.host }}/login"
            - name: AUTHENTICATION_JWT_SECRET
              valueFrom:
                  secretKeyRef:
                    name: {{ .Values.authenticationJwtSecret | quote }}
                    key: reviewer-auth-secret
              value: {{ .Values.submission.authSecret | quote }}
            - name: CONTINUUM_JWT_SECRET
              valueFrom:
                  secretKeyRef:
                    name: {{ .Values.continuumAdaptor.continuumJwtSecret | quote }}
                    key: continuumJwtSecret
            - name: CONTINUUM_API_URL
              value: {{ .Values.continuumAdaptor.continuumApiUrl | quote }}
            - name: ELIFE_API_GATEWAY_SECRET
              valueFrom:
                  secretKeyRef:
                    name: {{ .Values.continuumAdaptor.elifeApiSecret | quote }}
                    key: token

            - name: DATABASE_NAME
              value: {{ .Values.postgresql.postgresqlDatabase | quote }}
            - name: DATABASE_USER
              value: {{ .Values.postgresql.postgresqlUsername | quote }}
            - name: DATABASE_PASSWORD
              valueFrom:
                  secretKeyRef:
                    name: {{ .Values.postgresql.existingSecret | quote }}
                    key: postgresql-password
            - name: DATABASE_HOST
              value: "{{ include "libero-reviewer.fullname" . }}-postgresql"
            - name: DATABASE_PORT
              value: "5432"
