{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "libero-reviewer.fullname" . }}-login
  labels:
    app.kubernetes.io/name: {{ include "libero-reviewer.name" . }}
    helm.sh/chart: {{ include "libero-reviewer.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    nginx.ingress.kubernetes.io/permanent-redirect: "{{ .Values.continuumAdaptor.loginUrl }}?return_url=https%3A%2F%2F{{ .Values.ingress.host }}%2Fauthenticate&token_in_query=true"
{{- with .Values.ingress.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .Values.ingress.login.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /continuum-login
            backend:
              serviceName: {{ printf "%s--%s" (include "libero-reviewer.fullname" . ) ("continuum-adaptor") }}
              servicePort: {{ .Values.continuumAdaptor.port}}
{{- end -}}
