version: '3'
services:
  continuum-adaptor:
    image: liberoadmin/continuum-adaptor:master-e036f03f-20200518.1618
    ports:
      - "3001:3001"
    healthcheck:
      test: 'echo -e "GET /health\n\n" | nc localhost:3001'
      interval: 2s
      timeout: 10s
      retries: 3
    environment:
      PORT: 3001
      LOGIN_URL: http://localhost:9000/submit
      LOGIN_RETURN_URL: http://localhost:9000/login
      AUTHENTICATION_JWT_SECRET: super_secret_jam
      CONTINUUM_JWT_SECRET: some_secret_from_journal
      CONTINUUM_API_URL: http://reviewer-mocks:3003
      DATABASE_NAME: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      ELIFE_API_GATEWAY_SECRET: ${ELIFE_API_GATEWAY_SECRET}
    networks:
      - infra_api
      - infra_postgres

  reviewer-mocks:
    image: liberoadmin/reviewer-mocks:master-b4b10cea-20200520.0835
    ports:
      - "3003:3003"
    healthcheck:
      test: 'echo -e "GET /health\n\n" | nc localhost:3003'
      interval: 2s
      timeout: 10s
      retries: 3
    volumes:
      - ./config/reviewer-mocks:/etc/reviewer:z
    networks:
      - infra_api

  submission:
    image: liberoadmin/reviewer-submission:master-4c0a1584-20200520.1045
    environment:
      NEW_RELIC_HOME: /etc/reviewer
      DATABASE_NAME: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      S3_AWS_ENDPOINT: http://s3:9000
      S3_ACCESS_KEY_ID: minio
      S3_SECRET_ACCESS_KEY: minio123
      S3_FORCE_PATH_STYLE: 'true'
      S3_FILE_BUCKET: test
      MAX_QL_COMPLEXITY: 100
      MAX_QL_DEPTH: 5
      MAX_FILE_SIZE_IN_BYTES: 100000000
      AUTHENTICATION_JWT_SECRET: super_secret_jam
      USER_API_URL: http://continuum-adaptor:3001
      SCIENCE_BEAM_URL: http://reviewer-mocks:3003/science-beam/convert
      SCIENCE_BEAM_TIMEOUT: 20000
    healthcheck:
      test: 'echo -e "GET /health\n\n" | nc localhost:3000'
      interval: 2s
      timeout: 10s
      retries: 3
    networks:
      - infra_postgres
      - infra_api

  client:
    image: liberoadmin/reviewer-client:master-07ee130c-20200520.1450
    healthcheck:
      interval: 2s
    networks:
      - infra_api

  nginx:
    image: nginx:stable-alpine@sha256:676b8117782d9e8c20af8e1b19356f64acc76c981f3a65c66e33a9874877892a
    networks:
      - "infra_api"
    ports:
      - '9000:9000'
    volumes:
      - ./config/proxy/nginx.conf:/etc/nginx/nginx.conf
    healthcheck:
      test: 'echo -e "GET /login\n\n" | nc localhost:9000'
      interval: 2s
    depends_on:
      - client
      - submission
      - reviewer-mocks
      - continuum-adaptor


networks:
  infra_postgres:
    external:
      name: "infra_postgres"
  infra_api:
    external:
      name: "infra_api"
