apiVersion: v2
appVersion: "latest"
description: elife specific deployment of Libero Reviewer
name: libero-reviewer
version: 0.14.8

dependencies:
  - name: "postgresql"
    version: "~6.2"
    repository: "https://kubernetes-charts.storage.googleapis.com/"
    condition: postgresql.enabled
